### ISSUE TITLE
Remove errorValues() test function

### ISSUE THREAD

**Issue by ralphtheninja** [Level/abstract-leveldown#266] opened 2018-07-11 22:54 UTC
https://github.com/Level/abstract-leveldown/blob/aa7e0b8142b759a019adb321a71ddcc4774113c6/test/put-get-del-test.js#L133-L134

It's been empty for quite a while, so either we implement something or remove it.

@vweevers WDYT?

**Comment by vweevers** [comment] 2018-07-12 07:36
Duplicate of #191.

**Closed by vweevers** 2018-07-12 07:36 UTC
